export const PROBUDA_NAME_UPDATE = 'PROBUDA_NAME_UPDATE'
export const PROBUDA_EMAIL_UPDATE = 'PROBUDA_EMAIL_UPDATE'
export const PROBUDA_PASSWORD_UPDATE = 'PROBUDA_PASSWORD_UPDATE'
export const PROBUDA_PASSWORD_CONFIRMATION_UPDATE = 'PROBUDA_PASSWORD_CONFIRMATION_UPDATE'
export const PROBUDA_LOGGED_IN = 'PROBUDA_LOGGED_IN'

